<?php 

use \Drupal\Core\Form\FormStateInterface;

/**
 * hook_form_alter()
 */
function mymodule_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ( $form_id == 'views_exposed_form' ) {

    if ($form['#id'] == 'views-exposed-form-test-view-block-1') {
      $form['title']['#autocomplete_route_name'] = 'myviewsfilters.autocomplete';
      // $form['title']['#prefix'] = "<div> {{ content.field_photos }}";
      // $form['title']['#suffix'] = "</div>";
    }

  }
	if ( $form_id == 'node_article_form' ) {
		$uid = \Drupal::currentUser()->id();
		//kint($form['title']);exit;
		if ( $uid == 1 ) {
			$form['title']['widget'][0]['value']['#default_value'] = 'Admin';
		} else {
			$form['title']['widget'][0]['value']['#default_value'] = 'Non-Admin';
		}
	}
	
}